### ISSUE TITLE
need conda installs for bluesky deps

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/vertical-integration#1]
Well after fighting with the horrible network issues here at NSLS-II, I am done with this for now. I need the conda installs for the bluesky epics-related dependencies and I am done trying to copy them from our internal conda to the public one so that travis can see them. Anyone else is welcome to jump in and make this happen.

**Comment by ericdill** [comment]
Man I really hate fighting with this network.  Here's the solution that I came up with
- vpn in to the campus network
- log in to anaconda.org
- log in to conda.nsls2.bnl.gov
- download all packages I need to my laptop
- `anaconda upload -u lightsource2 ~/Downloads/linux-64-*`
- add `conda install -c lightsource2 [all_the_packages]` to the travis yml file

[edit] I was not paying close attention and put the ~/Downloads/ in front of the wrong positional

**Comment by danielballan** [comment]
What does -u do here? I thought that was user.

**Comment by ericdill** [comment]
yeah i mistyped that. let me edit it
